### ISSUE TITLE
terminate called after throwing an instance of 'std::logic_error'

### ISSUE THREAD

**Issue by ptranvan** [mahulchak/quickmerge#35] opened 2018-10-03 20:34 UTC
Hi,

I have an issue after running `merge_wrapper.py `

```
4: FINISHING DATA
0       quickmerge
1       -d
2       out.rq.delta
3       -q
4       hybrid_oneline.fa
5       -r
6       self_oneline.fa
7       -hco
8       5.0
9       -c
10      1.5
11      -l
12      0
13      -ml
14      5000
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
```

**Comment by esolares** [comment] 2018-10-03 20:52
Hi

Please try using the prefix option. I will be pushing a fix for setting a
default prefix soon.

Thank you,

Edwin

**Comment by ptranvan** [comment] 2018-10-04 07:54
This is my command:

`merge_wrapper.py ../P1.fasta ../M1.fasta -pre P_query`

And I still have the error

**Comment by FAFUyangyang** [comment] 2018-10-13 06:29
i have the same question，I hope you can help me out，thank you。

**Comment by FAFUyangyang** [comment] 2018-10-13 06:29
> This is my command:
> 
> `merge_wrapper.py ../P1.fasta ../M1.fasta -pre P_query`
> 
> And I still have the error
Have you solved it？

**Comment by lfaller-zymergen** [comment] 2018-10-24 00:31
Hello all,

I am encountering the same error. Please advise!

Best,
~Lina

**Comment by joneill4x** [comment] 2018-10-29 18:46
I also have the same problem.  I made sure to add quickmerge/mummer to my PATH.

export PATH=/mnt/nas/software/quickmerge:/mnt/nas/software/quickmerge/MUMmer3.23:$PATH

**Comment by mahulchak** [comment] 2018-10-30 05:44
Did you try the quickmerge command line ? I think the problem is with the
wrapper so while we fix it, you could try the quickmerge stand-alone
version.

**Comment by jgbaldwinbrown** [comment] 2018-10-30 15:40
Hi all,

I wrote the wrapper a while ago. I believe I have now fixed the merge_wrapper error. The problem was that quickmerge was modified to require a '-p' option to supply an output prefix, but the wrapper wasn't modified to send the wrapper's '-pre' prefix on to quickmerge. Take another crack at using the wrapper and let me know if it isn't working.

**Comment by joneill4x** [comment] 2018-10-30 20:01
Thank you jgbaldwinbrown.

I would like to add, even though I added /the/path/to/quickmerge/MUMmer3.23/ to the $PATH variable, the version of MUMmer being called by the script was a 32 bit version.

I needed to do:

sudo apt-get purge mummer

Then place a 64 bit version of MUMmer in /usr/bin/ .

**Comment by jgbaldwinbrown** [comment] 2018-10-30 20:16
It sounds like the problem is solved, and we got some useful advice about making sure that the 64-bit version of MUMmer is in use. I'm going to close this up.

**Closed by jgbaldwinbrown** 2018-10-30 20:16 UTC

**Comment by esolares** [comment] 2018-10-30 20:30
Hi,

If you source the file that is created when you compile quickmerge, you
should have the 64bit version of MUMmer precede all other installations as
it does: PATH=MYMUMPATH:$PATH where MYMUMPATH is the location where 64bit
MUMmer is located.

After compiling quickmerge you should get a line at the bottom telling you
how to source the file. Also you can ls -al to see the file that needs to
be sourced prior to running quickmerge.

Please let us know if you have any more questions.

Thank you,

Edwin Solares, B.S.
Computational Biology
Department of Ecology and Evolutionary Biology
Gaut Lab
5438 McGaugh Hall
University of California, Irvine
Irvine, CA 92697
USA
